// The E2E coverage matrix: the frozen minimum of keyboard workflows the suite
// proves (issue #199). Rows may be added; none may be removed or weakened
// without the maintainer. `e2e/guards/run.ts` checks it against CONTEXT.md,
// the shortcut registry, App.tsx routes, and the specs before every run.

import type { Exclusion, MatrixRow } from "./guards/types";

const SYNC_FOLLOW_UP =
  "Vitest sync suites; follow-up issue: E2E Sync lane (local PocketBase 0.25.0 + maibuk-sync migrations) https://github.com/M4ss1ck/maibuk/issues/222";

export const EXCLUSIONS: Exclusion[] = [
  {
    kind: "term",
    items: ["Click by Name"],
    reason: "Decided, not built (ADR 0016); the #267 build adds its row",
    owner: "App-tier Voice Commands, https://github.com/M4ss1ck/maibuk/issues/267",
  },
  {
    kind: "context-section",
    section: "Sync",
    reason: "Sync is out of scope for this delivery (maintainer, 2026-09-25)",
    owner: SYNC_FOLLOW_UP,
  },
  {
    kind: "context-section",
    section: "Anticipated",
    reason: "Reserved names for features nobody has decided to build",
    owner: "none: nothing to test",
  },
  {
    kind: "shortcut",
    items: ["global.syncNow"],
    reason: "Sync is out of scope for this delivery",
    owner: SYNC_FOLLOW_UP,
  },
  {
    kind: "shortcut",
    items: ["global.toggleAlwaysOnTop"],
    reason: "Tauri-only window behavior; the web build has no always-on-top",
    owner: "Vitest platform tests, manual QA",
  },
  {
    kind: "term",
    items: ["Backup Directory"],
    reason:
      "Desktop-only: the web build keeps Backups in IndexedDB and has no directory (ADR 0010)",
    owner: "Vitest backup suites + Rust tests in src-tauri/src/backup.rs",
  },
  {
    kind: "term",
    items: ["Drawing"],
    reason: "Creating a Drawing and erasing are pointer gestures by nature (documented exemption)",
    owner: "Vitest canvas suites; keyboard tool switching is covered by canvas-tools",
  },
  {
    kind: "behavior",
    items: [
      "always on top",
      "close to tray",
      "launch on startup",
      "window state",
      "deep links",
      "Android back",
    ],
    reason: "Tauri or Android only; not reachable from the web build",
    owner: "Vitest platform tests, manual QA",
  },
  {
    kind: "behavior",
    items: ["Database File and Backup Directory native dialogs"],
    reason: "Desktop-only paths; the web build uses a download and a file input, which are covered",
    owner: "Vitest + ADR 0010 Rust tests",
  },
  {
    kind: "behavior",
    items: ["file drop gesture", "Canvas eraser"],
    reason: "Pointer gestures; keyboard Import controls cover the same outcome",
    owner: "Vitest (useTextFileDrop, EditorFileDrop)",
  },
  {
    kind: "behavior",
    items: ["phone viewport", "touch", "Item Menu long-press", "mobile navigation menu"],
    reason: "Desktop viewport only in this delivery (decision 11)",
    owner:
      "src/test/unit/touch-reachability.test.ts; follow-up issue: phone/touch E2E project https://github.com/M4ss1ck/maibuk/issues/223",
  },
  {
    kind: "behavior",
    items: ["OAuth2 login"],
    reason: "Needs a real identity provider",
    owner: "none",
  },
  {
    kind: "behavior",
    items: ["visual regression (pixel screenshots)"],
    reason: "Cross-engine text rendering makes pixel diffs flaky",
    owner: "Cover Layers panel and export dimension assertions",
  },
  {
    kind: "behavior",
    items: ["screen reader compatibility"],
    reason: "Browser automation cannot prove what a screen reader announces",
    owner: "manual NVDA and VoiceOver pass (not in this delivery)",
  },
];

export const ROWS: MatrixRow[] = [
  {
    id: "shell-nav-sidebar",
    area: "shell",
    workflow:
      "Tab into primary nav (nav.primary), Arrow/Tab through Books, Notes, Canvas, Ephemeral, Metrics, Settings; Enter navigates; asserts: Focused link; RouteAnnouncer live region text changes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/", "/notes", "/canvas", "/ephemeral", "/metrics", "/settings"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "shell-goto-sequences",
    area: "shell",
    workflow: "g p, g n, g c, g e, g m, g s from Home; asserts: URL + heading per route",
    edges: ["Sequences ignored while typing in an input (isTypingTarget)"],
    terms: [],
    shortcuts: [
      "global.gotoProjects",
      "global.gotoNotes",
      "global.gotoCanvas",
      "global.gotoEphemeral",
      "global.gotoMetrics",
      "global.gotoSettings",
    ],
    routes: ["/", "/notes", "/canvas", "/ephemeral", "/metrics", "/settings"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "shell-cycle-panes",
    area: "shell",
    workflow:
      "F6 / Shift+F6 cycles nav sidebar, main content, and on Book Editor: chapter list, editor, side panel; asserts: Focus lands in each labelled region (panes.*) in order, wraps",
    edges: [],
    terms: [],
    shortcuts: ["global.cyclePanesForward", "global.cyclePanesBackward"],
    routes: ["/", "/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "shell-toggle-theme",
    area: "shell",
    workflow:
      "g t toggles light/dark; asserts: html.dark toggles; Settings theme control agrees; persists: Reload keeps theme",
    edges: [],
    terms: [],
    shortcuts: ["global.toggleTheme"],
    routes: ["/", "/settings"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "shell-shortcut-hints",
    area: "shell",
    workflow:
      "g h toggles shortcut hints; asserts: Hint kbd elements appear/disappear; persists: Reload keeps",
    edges: [],
    terms: [],
    shortcuts: ["global.toggleShortcutHints"],
    routes: ["/"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "shell-help-dialog",
    area: "shell",
    workflow:
      '? opens Shortcuts help; lists "On this screen" and "On other screens"; Esc closes; asserts: Focus inside dialog on open, Tab contained, returns to prior element',
    edges: ['? typed inside editor inserts "?" and does not open help'],
    terms: [],
    shortcuts: ["global.showHelp"],
    routes: ["/", "/book/:bookId"],
    fixture: "empty",
    tags: ["mac-platform"],
    status: "accepted",
  },
  {
    id: "shell-help-bound-per-screen",
    area: "shell",
    workflow:
      'Open help on Home, Book Editor, Canvas, Cover, Notes: "On this screen" lists exactly that screen\'s Bound Shortcuts; asserts: Group names',
    edges: [],
    terms: ["Bound Shortcut"],
    shortcuts: [],
    routes: ["/", "/book/:bookId", "/canvas/:canvasId", "/book/:bookId/cover", "/notes/:noteId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "shortcut-editor",
    area: "shell",
    workflow:
      "Open the Shortcut Editor from Settings or the shortcut help; record a key, a sequence, or a key for a Command; Replace on a conflict; Reset one or all; Single-key Shortcuts switch; save and load a Shortcut File; asserts: the new key works and the old one does not, focus inside, Tab contained, Esc returns focus; persists: yes (device-local)",
    edges: [
      "Escape cancels recording without binding Escape or closing the editor",
      "A Fixed key is blocked and recording continues",
      "Opened from the shortcut help's Customize button",
      "An invalid Shortcut File changes nothing and shows an error",
      "A conflicting Shortcut File previews the dropped key",
    ],
    terms: [
      "Command",
      "Shortcut",
      "Default Shortcut",
      "Custom Shortcut",
      "Fixed Shortcut",
      "Sealed Command",
      "Shared Command",
      "Shortcut Context",
      "Shortcut Conflict",
      "Shortcut Editor",
      "Single-key Shortcuts",
      "Shortcut File",
    ],
    shortcuts: ["global.showHelp"],
    routes: ["/settings", "/", "/metrics", "/ephemeral"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "shell-help-start-tutorial",
    area: "shell",
    workflow:
      'Help dialog "Start tutorial for this screen" by keyboard; asserts: Tutorial card focused',
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "shell-restore-last-path",
    area: "shell",
    workflow:
      "Navigate to a Note, reload the app at /; asserts: StartupRedirect lands on last path; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/notes/:noteId", "/"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-empty-state",
    area: "books",
    workflow:
      "empty: Home shows empty state; its New Book button reachable by Tab, Enter opens dialog; asserts: books.noBooksButton focused, dialog title",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-library-load-error",
    area: "books",
    workflow:
      "the saved Library cannot be read at launch: Home shows libraryLoad.title and the error instead of the empty state; Try again reachable by Tab, Enter reloads and shows the Books; asserts: alert text, no empty-state heading, Book card visible after retry",
    edges: [],
    terms: ["Library"],
    shortcuts: [],
    routes: ["/"],
    fixture: "bookShelf",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-create",
    area: "books",
    workflow:
      "Alt+N (web) opens New Book; type title, Tab, Author Name, Enter creates and lands in the Book Editor with focus on Add Chapter; Enter, chapter title, Enter opens the Chapter with the caret in its text; type, Mod+S, Save Status Saved; reload keeps the text",
    edges: [
      "Esc cancels and restores focus to the New Book button",
      "empty title shows errors.titleRequired with focus on Book Title",
      "empty Author Name shows errors.authorNameRequired with focus on Author Name",
      "Tab stays inside the dialog",
    ],
    terms: ["Book", "Author Name", "Save Status"],
    shortcuts: ["bookList.newBook", "common.save"],
    routes: ["/", "/book/:bookId"],
    fixture: "empty",
    tags: ["mac-platform"],
    status: "accepted",
  },
  {
    id: "books-navigate-collection",
    area: "books",
    workflow:
      "Arrow keys and j/k move selection across book cards; Enter opens; asserts: activeElement moves card to card",
    edges: ["Home/End if supported"],
    terms: [],
    shortcuts: [
      "bookList.moveSelectionNext",
      "bookList.moveSelectionPrevious",
      "bookList.openSelected",
    ],
    routes: ["/", "/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-jump-number",
    area: "books",
    workflow: "Keys 1-9 open Nth book; asserts: Book Editor for that book",
    edges: ["Key ignored when fewer books"],
    terms: [],
    shortcuts: ["bookList.jumpBooks"],
    routes: ["/", "/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-status-filter",
    area: "books",
    workflow:
      'Book Status filter: open by keyboard, choose each status, "All statuses"; asserts: Filter announcement (books.filterAnnouncement) text; counts; persists: Reload keeps filter? (verify intended)',
    edges: ["No matches state books.noMatches"],
    terms: ["Book Status", "Gallery"],
    shortcuts: [],
    routes: ["/"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-change-status",
    area: "books",
    workflow:
      "Book actions Item Menu: open via keyboard, Change status submenu, pick In Progress; asserts: Menu focus, arrow moves, Esc closes submenu then menu, focus back to ⋯; persists: yes",
    edges: ["Toast books.statusChangedToast"],
    terms: ["Book Status"],
    shortcuts: [],
    routes: ["/"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-archive-unarchive",
    area: "books",
    workflow:
      'Set Archived: book hidden from default Gallery, toast; show Archived filter, Unarchive; asserts: Toast "Unarchived"; persists: yes',
    edges: [],
    terms: ["Archived", "Unarchive", "Book Status", "Gallery"],
    shortcuts: [],
    routes: ["/"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-settings-dialog",
    area: "books",
    workflow:
      "From Book Editor, Book Settings dialog: edit title, subtitle, author, genre, description, language, target word count, status; Save; asserts: Dialog focus entry/containment/restore; persists: yes",
    edges: ["Cancel discards", "invalid target word count"],
    terms: ["Author Name", "Genre", "Target Word Count", "Book", "Book Status"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-delete",
    area: "books",
    workflow:
      "Book Settings > Danger zone > Delete > confirm; asserts: Confirm dialog focus lands on safe action; after delete, focus on Gallery; persists: yes, gone",
    edges: ["Cancel keeps book"],
    terms: ["Book", "Gallery"],
    shortcuts: [],
    routes: ["/book/:bookId", "/"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "books-import-epub",
    area: "books",
    workflow:
      'Home "Import EPUB" button (keyboard) opens file chooser; setFiles(fixture.epub); Compatibility Report shows; acknowledge warnings; Import; asserts: Report dialog focus, acknowledge checkbox by Space; persists: yes: Book + Chapters exist',
    edges: ["Cancel imports nothing", "blocked EPUB shows block reason and Import disabled"],
    terms: ["Import", "Compatibility Report", "Book", "Chapter"],
    shortcuts: [],
    routes: ["/"],
    fixture: "oneBookThreeChapters",
    tags: ["filechooser"],
    status: "accepted",
  },
  {
    id: "books-import-md-txt",
    area: "books",
    workflow:
      "Import Markdown/plain text into a Book via keyboard-reachable control; asserts: Toast import.importedFile; persists: yes",
    edges: ["Unsupported file rejected with message"],
    terms: ["Import", "Book", "Chapter"],
    shortcuts: [],
    routes: ["/", "/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["filechooser"],
    status: "accepted",
  },
  {
    id: "chapters-add",
    area: "chapters",
    workflow:
      'Chapter list "Add chapter": type title, Enter; asserts: New chapter focused/opened; persists: yes',
    edges: ["Esc cancels create", "empty title behavior"],
    terms: ["Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-navigate",
    area: "chapters",
    workflow:
      "Arrow keys within chapter list, Enter opens chapter in editor; asserts: activeElement moves; editor shows chapter; persists: Last Opened Chapter: reload reopens it",
    edges: [],
    terms: ["Chapter", "Last Opened Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-rename-type",
    area: "chapters",
    workflow:
      "Chapter Item Menu > Edit: rename, set Chapter Type (Prologue, Part, Front/Back Matter); asserts: Menu then form focus; restored to row; persists: yes",
    edges: ["Cancel"],
    terms: ["Chapter", "Chapter Type", "Item Menu"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-reorder-keyboard",
    area: "chapters",
    workflow:
      "React Aria DnD keyboard path: focus row, start drag with Enter, arrows, Enter drops; asserts: Announcements, final order; persists: yes",
    edges: ["Esc cancels drag", "order unchanged"],
    terms: ["Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-delete",
    area: "chapters",
    workflow:
      "Item Menu > Delete > confirm Yes; asserts: Focus moves to neighbor row; persists: yes",
    edges: ['"No" keeps it', "deleting the open chapter opens another"],
    terms: ["Chapter", "Item Menu"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-compact-view",
    area: "chapters",
    workflow:
      "Toggle compact/normal list view by keyboard; asserts: Button pressed state + layout; persists: yes?",
    edges: [],
    terms: ["Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-toggle-sidebar",
    area: "chapters",
    workflow: "Mod+\\ hides/shows chapter sidebar; asserts: Focus not lost to body",
    edges: [],
    terms: ["Chapter"],
    shortcuts: ["bookEditor.toggleSidebar"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-status-display",
    area: "chapters",
    workflow: "Chapter Status shown on rows; asserts: text",
    edges: [],
    terms: ["Chapter Status", "Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-status-set",
    area: "chapters",
    workflow:
      "Set a Chapter's Status from its Item Menu: open the menu by keyboard, arrow to Status, ArrowRight, arrow to Revised, Enter; asserts: row text, submenu focus, focus back on the row; persists: yes",
    edges: [],
    terms: ["Chapter Status", "Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-back",
    area: "chapters",
    workflow:
      "Backspace outside editor returns to Book Gallery; Backspace in editor deletes text only; asserts: URL",
    edges: ["Critical: Backspace in text must not navigate"],
    terms: ["Gallery", "Book", "Chapter"],
    shortcuts: ["common.back"],
    routes: ["/book/:bookId", "/"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "chapters-word-count",
    area: "chapters",
    workflow: "Typing updates word and char counts; selection stats; asserts: status bar text",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-type-save",
    area: "editor",
    workflow:
      "Type, Save Status goes Saving -> Saved; Mod+S saves immediately; asserts: Save Status text; persists: yes",
    edges: ['Failed save shows "Not saved" (inject IndexedDB quota failure? verify feasibility)'],
    terms: ["Save Status", "Edit Session"],
    shortcuts: ["common.save"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-keymap-marks",
    area: "editor",
    workflow:
      "Each mark shortcut on selected text: bold, italic, underline, strikethrough, highlight, subscript, superscript, code; asserts: Toolbar button pressed state reflects mark; persists: yes",
    edges: ["Shortcut toggles off on second press"],
    terms: [],
    shortcuts: [
      "editor.bold",
      "editor.italic",
      "editor.underline",
      "editor.strikethrough",
      "editor.highlight",
      "editor.subscript",
      "editor.superscript",
      "editor.code",
    ],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-keymap-blocks",
    area: "editor",
    workflow:
      "Heading 1-3, bullet, numbered, task list, quote, code block via shortcuts; asserts: DOM structure in editor; persists: yes",
    edges: [],
    terms: ["Heading"],
    shortcuts: [
      "editor.heading1",
      "editor.heading2",
      "editor.heading3",
      "editor.bulletList",
      "editor.numberedList",
      "editor.taskList",
      "editor.quote",
      "editor.codeBlock",
    ],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-keymap-align-indent",
    area: "editor",
    workflow: "Align left/center/right/justify; Tab/Shift+Tab indent in lists; persists: yes",
    edges: [
      "Tab outside list: does not trap focus forever (Esc then Tab leaves editor, verify documented behavior)",
    ],
    terms: [],
    shortcuts: [
      "editor.alignLeft",
      "editor.alignCenter",
      "editor.alignRight",
      "editor.alignJustify",
      "editor.increaseIndent",
      "editor.decreaseIndent",
    ],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-undo-redo",
    area: "editor",
    workflow: "Mod+Z / Mod+Shift+Z; asserts: text",
    edges: [],
    terms: [],
    shortcuts: ["common.undo", "common.redo"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-markdown-input-rules",
    area: "editor",
    workflow: "Typing # , - , > , **x** converts; asserts: structure; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-no-global-leak",
    area: "editor",
    workflow:
      "Inside editor: ?, 1-9, g p, j/k, V/P/E/T/N letters, Backspace type text; no navigation, no help dialog; asserts: URL unchanged, dialog absent",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-toolbar-nav",
    area: "editor",
    workflow:
      "Tab reaches toolbar once; Arrow keys move between buttons (roving); Enter/Space activate; Esc returns to editor; asserts: activeElement per arrow",
    edges: ['Overflow "More" group opens by keyboard'],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-toolbar-selects",
    area: "editor",
    workflow:
      "Font family, font size, line height, text color picker via keyboard; asserts: value applied to selection; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-toolbar-settings",
    area: "editor",
    workflow:
      "Mod+Shift+, opens Toolbar Settings; reorder items with Move up/down and keyboard DnD; toggle visibility; add divider; reset (confirm); asserts: Dialog focus; order; persists: yes (settings)",
    edges: ["Reset cancel"],
    terms: [],
    shortcuts: ["editor.toolbarSettings"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-selection-toolbar",
    area: "editor",
    workflow:
      "Shift+Arrows selects text and shows the selection toolbar; Alt+F10 focuses it; arrows/Home/End move; Enter applies Bold keeping focus and selection; Esc returns to the text; Link dialog returns focus to the text; asserts: toolbar focus; selection kept; selection painted while the toolbar has focus",
    edges: [
      "Link dialog Esc returns to the text",
      "group only in the floating toolbar",
      "selection stays visible while the toolbar has focus",
      "highlight picker from the bubble keeps the selection painted",
    ],
    terms: [],
    shortcuts: ["editor.focusSelectionToolbar"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-context-menu",
    area: "editor",
    workflow:
      "Shift+F10 / ContextMenu key opens editor context menu; arrow, Enter runs action (e.g., Paste without formatting, Remove formatting); asserts: Menu focus; Esc returns to caret",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-link-dialog",
    area: "editor",
    workflow:
      "Mod+K opens Link dialog; type URL/choose internal target (Book, Chapter, Note, Heading); Enter inserts; asserts: Dialog focus/restore to editor caret; persists: yes",
    edges: ["Esc cancels", "invalid URL"],
    terms: ["Link", "Book", "Chapter", "Note", "Heading"],
    shortcuts: ["editor.insertLink"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-wikilink-suggest",
    area: "editor",
    workflow:
      "Type [[, suggestion list, arrows, Enter inserts Link; asserts: Listbox active option; persists: yes",
    edges: ["Esc closes list"],
    terms: ["Link"],
    shortcuts: [],
    routes: ["/notes/:noteId"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-follow-link",
    area: "editor",
    workflow: "Keyboard activation of a Link opens target (Note/Chapter); asserts: URL/editor",
    edges: ["Missing target", "Heading in the same Note"],
    terms: ["Link", "Note", "Chapter"],
    shortcuts: ["editor.followLink"],
    routes: ["/book/:bookId", "/notes/:noteId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-image-insert",
    area: "editor",
    workflow:
      "Insert image dialog: file chooser from keyboard; URL alternative; asserts: Dialog focus; persists: yes",
    edges: ["Cancel"],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["filechooser"],
    status: "accepted",
  },
  {
    id: "editor-image-menu",
    area: "editor",
    workflow: "Image context menu by keyboard: resize/align/delete; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-footnote",
    area: "editor",
    workflow:
      "Insert Footnote (toolbar/menu) opens dialog; type text; Enter; Footnotes view lists it; edit and delete from each list's Item Menu; asserts: Dialog focus; side panel Footnotes tab; focus returns to the entry; persists: yes",
    edges: [
      "Cancel inserts nothing",
      "Escape in the Edit dialog changes nothing and returns focus to the entry",
      "Undo restores a Footnote deleted from the list, with its text",
      "edit and delete a Footnote from the side panel's Footnotes tab",
    ],
    terms: ["Footnote"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-scene-break",
    area: "editor",
    workflow:
      "Insert Scene Break (symbol and image variants); Scene Break menu by keyboard; persists: yes",
    edges: [],
    terms: ["Scene Break"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-outline",
    area: "editor",
    workflow:
      "Show outline toggle; outline lists headings and Scene Breaks; arrow + Enter jumps caret there; asserts: Outline item focus, caret position",
    edges: ["Empty outline state"],
    terms: ["Outline", "Heading", "Scene Break"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-table",
    area: "editor",
    workflow:
      "TableSizePicker via arrows + Enter inserts NxM; Table menu add/remove row/column by keyboard; asserts: Grid picker active cell; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-find-replace",
    area: "editor",
    workflow:
      "Mod+F opens; type; Enter next, Shift+Enter previous; replace, replace all; Esc closes and returns focus to editor; asserts: Match counter text; persists: yes after replace",
    edges: ["No matches"],
    terms: [],
    shortcuts: ["common.find", "editor.findNext", "editor.findPrevious", "editor.closeFindReplace"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-symbols",
    area: "editor",
    workflow:
      "Mod+Shift+O opens Symbols dialog; search, arrow grid, Enter inserts; : autocomplete suggestion; asserts: Grid focus; persists: yes",
    edges: ["Esc"],
    terms: ["Symbol"],
    shortcuts: ["editor.insertSymbol"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-text-case",
    area: "editor",
    workflow: "Text Case menu: upper, lower, mirrored on selection; persists: yes",
    edges: [],
    terms: ["Text Case"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-spell-check",
    area: "editor",
    workflow:
      "Misspelled word marked; keyboard path to suggestions popover; Add to dictionary; persists: Custom Dictionary persists",
    edges: [],
    terms: ["Spell Check", "Custom Dictionary"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-custom-dictionary",
    area: "editor",
    workflow:
      "Mod+Shift+D opens Dictionary dialog; add/remove word; Settings Custom Dictionary edit; asserts: Dialog focus; persists: yes",
    edges: ["Duplicate word"],
    terms: ["Custom Dictionary", "Spell Check"],
    shortcuts: ["editor.dictionary"],
    routes: ["/book/:bookId", "/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-word-lookup",
    area: "editor",
    workflow: '"Look up word" on selection; asserts: Word Lookup UI',
    edges: ["Offline/unavailable message"],
    terms: ["Word Lookup"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["simulated"],
    status: "accepted",
  },
  {
    id: "editor-paste-cleanup",
    area: "editor",
    workflow:
      'Paste HTML via real Mod+V; "Match my book" preset strips styles; asserts: resulting HTML; persists: yes',
    edges: ["Paste without formatting"],
    terms: ["Paste Cleanup"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
  {
    id: "editor-markdown-paste",
    area: "editor",
    workflow:
      "Paste markdown text; MarkdownPasteDialog asks; choose convert / keep; asserts: Dialog focus; persists: yes",
    edges: ["Esc keeps plain"],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
  {
    id: "editor-copy",
    area: "editor",
    workflow: "Mod+C of formatted selection puts HTML+text on clipboard; asserts: clipboard read",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
  {
    id: "editor-html-view",
    area: "editor",
    workflow:
      "View HTML panel (CodeMirror): open, edit HTML, apply; Inspect in HTML; asserts: Focus in CodeMirror, Esc returns; persists: yes",
    edges: ["Invalid HTML validation message"],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-code-block",
    area: "editor",
    workflow: "Code block language select by keyboard; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-collapsible-heading",
    area: "editor",
    workflow: "Collapse/expand heading by keyboard; persists: collapsed state persists (Notes)",
    edges: [],
    terms: ["Heading"],
    shortcuts: ["editor.toggleHeadingCollapse"],
    routes: ["/notes/:noteId"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-zoom-width",
    area: "editor",
    workflow:
      "Mod+= / Mod+- / Mod+0 zoom; width control and page padding by keyboard; asserts: zoom % text; persists: yes",
    edges: [],
    terms: [],
    shortcuts: ["common.zoomIn", "common.zoomOut", "editor.zoomReset"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-focus-mode",
    area: "editor",
    workflow:
      'F11 enters Focus Mode, chrome hidden; Esc / "Exit focus" leaves; focus stays in editor',
    edges: ["Escape leaves Focus Mode"],
    terms: ["Focus Mode"],
    shortcuts: ["bookEditor.focusMode", "bookEditor.leavePanel"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "editor-export-chapter",
    area: "editor",
    workflow:
      'Chapter export: Markdown, PDF, image from "More" menu; asserts: [download] content checked',
    edges: ["Failure toast"],
    terms: ["Export", "Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["download"],
    status: "accepted",
  },
  {
    id: "editor-reading-position",
    area: "editor",
    workflow:
      "Caret + scroll restored after leaving and reopening a chapter; asserts: caret offset; persists: yes (device-local)",
    edges: [],
    terms: ["Reading Position", "Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "sidepanel-open-tabs",
    area: "side-panel",
    workflow:
      "Open Book Notes panel from editor, switch Notes/Footnotes tabs with arrows; asserts: Tab focus",
    edges: ["Close returns focus"],
    terms: ["Book Note", "Footnote"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "sidepanel-resize",
    area: "side-panel",
    workflow: "Resize handle by keyboard arrows; asserts: width; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "booknotes-add-quick",
    area: "side-panel",
    workflow:
      "Add Book Note, type in Quick Note editor with its formatting shortcuts; persists: yes",
    edges: ["Empty state"],
    terms: ["Book Note", "Note"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "booknotes-open-full",
    area: "side-panel",
    workflow: 'Open a Book Note in Notes screen and "Back to book"; asserts: URL, focus',
    edges: [],
    terms: ["Book Note", "Note"],
    shortcuts: [],
    routes: ["/book/:bookId", "/notes/:noteId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-gallery-browse",
    area: "notes",
    workflow: "Notes Gallery: arrow through cards, Enter opens; asserts: activeElement",
    edges: ["Empty state", "ArrowDown from the page enters the first card"],
    terms: ["Gallery", "Note"],
    shortcuts: ["notes.enterList"],
    routes: ["/notes"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-create",
    area: "notes",
    workflow:
      "New note from Gallery and from Notes list; title + body; asserts: Editor focus; persists: yes",
    edges: ["Untitled fallback title"],
    terms: ["Note", "Unfiled Note", "Gallery"],
    shortcuts: [],
    routes: ["/notes", "/notes/:noteId"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-search-filter",
    area: "notes",
    workflow:
      "Search text; Tag filter; exclude Tag; date range via date picker keyboard; clear filters; asserts: Result count text",
    edges: [
      "No matches state",
      "Mod+Shift+F opens the advanced filters with focus inside the tag filter",
    ],
    terms: ["Tag", "Note"],
    shortcuts: ["notes.advancedFilters"],
    routes: ["/notes"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-list-group-sort",
    area: "notes",
    workflow:
      "Notes list: group by book/date/tag; list vs tree view; sort menu by keyboard; asserts: Menu focus; persists: yes",
    edges: [],
    terms: ["Note", "Book", "Tag"],
    shortcuts: [],
    routes: ["/notes", "/notes/:noteId"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-item-menu",
    area: "notes",
    workflow:
      "Note Item Menu via ⋯ and Shift+F10: rename, duplicate, pin/unpin, move to Book, delete; asserts: Menu focus; restore to ⋯; persists: yes",
    edges: ["Delete confirm Cancel"],
    terms: ["Note", "Item Menu", "Pinned", "Book Note"],
    shortcuts: [],
    routes: ["/notes", "/notes/:noteId"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-pin-order",
    area: "notes",
    workflow:
      "Pinned note appears in Pinned section / top of Gallery; asserts: order; persists: yes",
    edges: [],
    terms: ["Pinned", "Note", "Gallery"],
    shortcuts: [],
    routes: ["/notes"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-move-to-book",
    area: "notes",
    workflow:
      "Move Unfiled Note to Book, appears in Book Notes; move back to Unfiled; persists: yes",
    edges: [],
    terms: ["Unfiled Note", "Book", "Book Note", "Note"],
    shortcuts: [],
    routes: ["/notes"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-reorder-keyboard",
    area: "notes",
    workflow: "Keyboard drag-and-drop in notes list (placement); asserts: order; persists: yes",
    edges: ["Esc cancels", "drop among Pinned Notes pins"],
    terms: ["Note", "Pinned"],
    shortcuts: [],
    routes: ["/notes"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-tags-edit",
    area: "notes",
    workflow: "Add Tag, remove Tag by keyboard in TagEditor; asserts: chips; persists: yes",
    edges: ["Duplicate tag"],
    terms: ["Tag", "Note"],
    shortcuts: [],
    routes: ["/notes"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-links-backlinks",
    area: "notes",
    workflow: 'Link Note A -> Note B; open B, "Linked from" lists A; Enter opens A; persists: yes',
    edges: ["Deleting A removes Backlink"],
    terms: ["Link", "Backlink", "Note"],
    shortcuts: [],
    routes: ["/notes/:noteId", "/notes"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-delete",
    area: "notes",
    workflow: "Delete Note dialog focus, confirm; asserts: Focus to neighbor; persists: yes",
    edges: ["Cancel"],
    terms: ["Note"],
    shortcuts: [],
    routes: ["/notes"],
    fixture: "notesWithLinksAndTags",
    tags: [],
    status: "accepted",
  },
  {
    id: "notes-last-edited",
    area: "notes",
    workflow:
      "Editing body/title moves Last Edited; pin/tag does not; asserts: card timestamp with fixed clock; persists: yes",
    edges: [],
    terms: ["Last Edited", "Note", "Pinned", "Tag"],
    shortcuts: [],
    routes: ["/notes"],
    fixture: "notesWithLinksAndTags",
    tags: ["clock"],
    status: "accepted",
  },
  {
    id: "notes-export",
    area: "notes",
    workflow: "Note export Markdown/PDF/image; asserts: [download]",
    edges: [],
    terms: ["Export", "Note"],
    shortcuts: [],
    routes: ["/notes/:noteId"],
    fixture: "notesWithLinksAndTags",
    tags: ["download"],
    status: "accepted",
  },
  {
    id: "ephemeral-write",
    area: "ephemeral",
    workflow:
      "Navigate by keyboard, focus lands in editor, type; asserts: word count; persists: Reload: text gone (never saved)",
    edges: [],
    terms: ["Ephemeral"],
    shortcuts: [],
    routes: ["/ephemeral"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "ephemeral-to-note",
    area: "ephemeral",
    workflow: '"Create note" turns text into a Note; opens it; persists: yes, Note exists',
    edges: ["Empty buffer: button disabled"],
    terms: ["Ephemeral", "Note"],
    shortcuts: [],
    routes: ["/ephemeral", "/notes/:noteId"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "ephemeral-clear",
    area: "ephemeral",
    workflow: "Clear buffer",
    edges: [],
    terms: ["Ephemeral"],
    shortcuts: [],
    routes: ["/ephemeral"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-gallery",
    area: "canvas",
    workflow:
      "Create, rename, pin/unpin, delete (confirm) Canvas; search; arrow + Enter open; asserts: Card focus; persists: yes",
    edges: ["Empty", "no matches", "delete cancel"],
    terms: ["Canvas", "Pinned"],
    shortcuts: [],
    routes: ["/canvas", "/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-tools",
    area: "canvas",
    workflow:
      "V, P, E, T, N shortcuts switch tool / add Text Node / add Note Reference; tool panel arrow navigation; asserts: Pressed tool state",
    edges: ["Letters inside a Text Node type text, don't switch tools"],
    terms: ["Canvas", "Text Node", "Note Reference"],
    shortcuts: [
      "canvas.toolSelect",
      "canvas.toolPen",
      "canvas.toolEraser",
      "canvas.addTextNode",
      "canvas.addNoteRef",
    ],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-text-node",
    area: "canvas",
    workflow:
      "T adds Text Node; type rich text with formatting shortcuts; Esc leaves text editing, node stays selected; asserts: Node focus; persists: yes",
    edges: ["Empty node"],
    terms: ["Text Node", "Canvas"],
    shortcuts: ["canvas.editTextNode"],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-note-ref",
    area: "canvas",
    workflow:
      "N opens note search; arrows + Enter adds Note Reference; Enter on reference opens Note; asserts: Search listbox; persists: yes",
    edges: ["No notes state", 'Missing Note Reference after Note deleted shows "Missing note"'],
    terms: ["Note Reference", "Missing Note Reference", "Note", "Canvas"],
    shortcuts: ["canvas.addNoteRef"],
    routes: ["/canvas/:canvasId", "/notes/:noteId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-node-select-move",
    area: "canvas",
    workflow:
      "Tab/arrow between nodes; arrow keys move selected node; asserts: node position; persists: yes",
    edges: [
      "Escape clears the node selection",
      "Alt+ArrowLeft returns to the Canvas gallery (URL /canvas and the gallery heading)",
    ],
    terms: ["Canvas"],
    shortcuts: ["canvas.clearSelection", "canvas.backToGallery"],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-connect",
    area: "canvas",
    workflow:
      '"Connect to" dialog from node: search target, Enter creates Connection; asserts: Dialog focus/restore; persists: yes',
    edges: ["No targets state"],
    terms: ["Connection", "Canvas"],
    shortcuts: [],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-edge-inspector",
    area: "canvas",
    workflow:
      "Open Connection inspector by keyboard; edit caption, toggle direction, delete; asserts: Card focus, Esc closes; persists: yes",
    edges: [],
    terms: ["Connection", "Canvas"],
    shortcuts: [],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-node-colors",
    area: "canvas",
    workflow: "Node color panel by keyboard: color pair, custom colors, transparent; persists: yes",
    edges: [],
    terms: ["Canvas", "Text Node"],
    shortcuts: [],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-delete-undo",
    area: "canvas",
    workflow: "Delete selection; undo/redo buttons and shortcuts; persists: yes",
    edges: [],
    terms: ["Canvas"],
    shortcuts: [],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-zoom-fit-lock",
    area: "canvas",
    workflow:
      "Mod+= / Mod+- / Shift+1 / L; asserts: viewport, lock state; persists: Reading Position pan/zoom restored",
    edges: [],
    terms: ["Reading Position", "Canvas"],
    shortcuts: ["common.zoomIn", "common.zoomOut", "canvas.fitView", "canvas.lock"],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-save-status",
    area: "canvas",
    workflow: "Save Status unsaved -> saving -> saved; asserts: text; persists: yes",
    edges: [],
    terms: ["Save Status", "Canvas"],
    shortcuts: [],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-rename-back",
    area: "canvas",
    workflow: "Rename in header; back to Gallery by keyboard; persists: yes",
    edges: [],
    terms: ["Canvas", "Gallery"],
    shortcuts: [],
    routes: ["/canvas/:canvasId", "/canvas"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "canvas-missing",
    area: "canvas",
    workflow: 'Open deleted canvas URL: "missing canvas", replace with empty canvas',
    edges: [],
    terms: ["Canvas"],
    shortcuts: [],
    routes: ["/canvas/:canvasId"],
    fixture: "canvasWithNodes",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-open",
    area: "cover",
    workflow: 'From Book Editor "Design cover" by keyboard; asserts: URL, focus on toolbar/back',
    edges: [],
    terms: ["Cover Designer", "Cover", "Book"],
    shortcuts: [],
    routes: ["/book/:bookId", "/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-templates",
    area: "cover",
    workflow:
      "Templates menu: arrows + Enter applies Cover Template with book title/author; asserts: Canvas objects present (assert via layers panel names); persists: yes after Mod+S",
    edges: [],
    terms: ["Cover Template", "Cover"],
    shortcuts: [],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-size-preset",
    area: "cover",
    workflow: "Choose Cover Size Preset; asserts: size values; persists: yes",
    edges: [],
    terms: ["Cover Size Preset", "Cover"],
    shortcuts: [],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-add-objects",
    area: "cover",
    workflow:
      "Add text, shape (rect/ellipse/line), image (filechooser), title/subtitle/author blocks; asserts: Layers panel lists new layer, focused?; persists: yes",
    edges: [],
    terms: ["Cover", "Author Name"],
    shortcuts: [],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: ["filechooser"],
    status: "accepted",
  },
  {
    id: "cover-select-layer",
    area: "cover",
    workflow:
      "Select object through Layers panel by keyboard; toggle lock/visibility; reorder up/down; asserts: Layer row focus; persists: yes",
    edges: [
      "] brings the selected layer forward and [ sends it back, changing the list order",
      "Escape clears the selection and the object's properties close",
    ],
    terms: ["Cover"],
    shortcuts: [
      "coverDesigner.sendBackward",
      "coverDesigner.bringForward",
      "coverDesigner.clearSelection",
    ],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-properties",
    area: "cover",
    workflow:
      "Edit properties (fill/paint gradient stops, stroke, font, size, rotation, opacity, shadow, filters) by keyboard; asserts: values; persists: yes",
    edges: [],
    terms: ["Cover"],
    shortcuts: [],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-nudge-position",
    area: "cover",
    workflow:
      "Move selected object with arrow keys (or X/Y fields); asserts: position; persists: yes",
    edges: ["Each arrow nudges 1 px; Shift+arrow leaps 10 px"],
    terms: ["Cover"],
    shortcuts: [
      "coverDesigner.nudgeUp",
      "coverDesigner.nudgeDown",
      "coverDesigner.nudgeLeft",
      "coverDesigner.nudgeRight",
      "coverDesigner.nudgeUpFar",
      "coverDesigner.nudgeDownFar",
      "coverDesigner.nudgeLeftFar",
      "coverDesigner.nudgeRightFar",
    ],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-align",
    area: "cover",
    workflow: "Align left/center/right/top/middle/bottom; persists: yes",
    edges: [],
    terms: ["Cover"],
    shortcuts: [],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-shortcuts",
    area: "cover",
    workflow: "Mod+S save, Delete, Mod+Z/Mod+Shift+Z, Mod+D; asserts: layer count; persists: yes",
    edges: ["Delete while typing in a property field edits the field, doesn't delete object"],
    terms: ["Cover"],
    shortcuts: [
      "common.save",
      "common.delete",
      "common.undo",
      "common.redo",
      "coverDesigner.duplicate",
    ],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-background",
    area: "cover",
    workflow: "Background color/image, remove image, opacity; persists: yes",
    edges: [],
    terms: ["Cover"],
    shortcuts: [],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-overlays-snapping",
    area: "cover",
    workflow: "Toggle overlays and snapping; asserts: pressed state",
    edges: [],
    terms: ["Cover"],
    shortcuts: [],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "cover-export",
    area: "cover",
    workflow: "Export PNG/JPG/PDF; asserts: [download] header/dimensions checked",
    edges: [],
    terms: ["Export", "Cover"],
    shortcuts: [],
    routes: ["/book/:bookId/cover"],
    fixture: "oneBookThreeChapters",
    tags: ["download"],
    status: "accepted",
  },
  {
    id: "cover-back-unsaved",
    area: "cover",
    workflow: "Back with unsaved changes; asserts: whatever the app does (verify)",
    edges: [],
    terms: ["Cover"],
    shortcuts: [],
    routes: ["/book/:bookId/cover", "/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "versions-save-named",
    area: "history",
    workflow:
      'Mod+Alt+S opens name prompt; type name; Enter; "Named" badge in history; asserts: Prompt focus/restore; persists: yes',
    edges: ["Esc cancels", "no changes -> versions.alreadyUpToDate"],
    terms: ["Named Version", "Version"],
    shortcuts: ["bookEditor.saveVersion"],
    routes: ["/book/:bookId"],
    fixture: "checkpointHistory",
    tags: [],
    status: "accepted",
  },
  {
    id: "versions-open-history",
    area: "history",
    workflow:
      "g v and History menu button open Version history panel; arrow through list; asserts: List focus",
    edges: ["Empty state", "pagination next/previous"],
    terms: ["Version"],
    shortcuts: ["bookEditor.versionHistory"],
    routes: ["/book/:bookId"],
    fixture: "checkpointHistory",
    tags: [],
    status: "accepted",
  },
  {
    id: "versions-checkpoint-idle",
    area: "history",
    workflow: 'Edit, advance clock past idle threshold: "Auto checkpoint" appears; persists: yes',
    edges: [],
    terms: ["Checkpoint", "Version", "Version Trigger"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "checkpointHistory",
    tags: ["clock"],
    status: "accepted",
  },
  {
    id: "versions-checkpoint-close",
    area: "history",
    workflow: 'Leave the Book Editor: "On close" checkpoint; persists: yes',
    edges: [],
    terms: ["Checkpoint", "Version Trigger", "Version"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "checkpointHistory",
    tags: [],
    status: "accepted",
  },
  {
    id: "versions-preview",
    area: "history",
    workflow: "Open a Version preview; asserts: chapter text",
    edges: [],
    terms: ["Version"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "checkpointHistory",
    tags: [],
    status: "accepted",
  },
  {
    id: "versions-compare",
    area: "history",
    workflow: "Compare to current: added/removed chapters, text diff; asserts: Compare view text",
    edges: ["No changes", "compare unavailable"],
    terms: ["Compare", "Version", "Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "checkpointHistory",
    tags: [],
    status: "accepted",
  },
  {
    id: "versions-restore",
    area: "history",
    workflow:
      'Restore > confirm: "Before restore" checkpoint created, content replaced, success toast, editor shows restored text; asserts: Confirm dialog focus; persists: yes',
    edges: [
      "Cancel",
      "restore with unsaved typing flushes first (typed text in pre-restore Checkpoint)",
    ],
    terms: ["Version", "Restore", "Flush", "Checkpoint"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "checkpointHistory",
    tags: [],
    status: "accepted",
  },
  {
    id: "versions-rename-delete",
    area: "history",
    workflow: "Rename and delete a Version (confirm); persists: yes",
    edges: ["Cancel"],
    terms: ["Version"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "checkpointHistory",
    tags: [],
    status: "accepted",
  },
  {
    id: "export-book-epub",
    area: "library-data",
    workflow:
      "Export dialog by keyboard: EPUB with TOC, numbered chapters, Maibuk styles; asserts: Dialog focus; radio/checkbox by Space",
    edges: ["Cancel"],
    terms: ["Export", "Table of Contents", "Book", "Chapter"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["download"],
    status: "accepted",
  },
  {
    id: "export-book-pdf",
    area: "library-data",
    workflow: "PDF: page size, margins, page numbers",
    edges: ["Failure toast"],
    terms: ["Export", "Book"],
    shortcuts: [],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["download"],
    status: "accepted",
  },
  {
    id: "backup-create-list",
    area: "library-data",
    workflow:
      'Settings > Backups: Create backup; row appears with trigger "Manual", localized date; asserts: Table row focus, toast; persists: yes',
    edges: [],
    terms: ["Backup", "Backup Trigger"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "backupsPresent",
    tags: [],
    status: "accepted",
  },
  {
    id: "backup-select-delete",
    area: "library-data",
    workflow:
      "Select rows (Space on checkbox), select all on page, delete selected (confirm); asserts: Checkbox state, count text; persists: yes",
    edges: ["Cancel", "pagination, items per page"],
    terms: ["Backup"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "backupsPresent",
    tags: [],
    status: "accepted",
  },
  {
    id: "backup-restore",
    area: "library-data",
    workflow:
      "Restore a Backup (confirm): pre-restore Backup created first, Library replaced, Canvases restored; asserts: Confirm focus; persists: yes",
    edges: [
      "Corrupt Backup (tampered checksum in IndexedDB) shows backup.backupCorrupt, data untouched",
    ],
    terms: ["Restore", "Backup", "Library"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "backupsPresent",
    tags: [],
    status: "accepted",
  },
  {
    id: "backup-retention",
    area: "library-data",
    workflow: 'Change "Maximum backups to keep", create beyond limit, oldest pruned; persists: yes',
    edges: ["Invalid value"],
    terms: ["Retention", "Backup"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "backupsPresent",
    tags: [],
    status: "accepted",
  },
  {
    id: "database-export",
    area: "library-data",
    workflow: "Export Database downloads file; asserts: [download] contents contain Books",
    edges: [],
    terms: ["Database File", "Book"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "backupsPresent",
    tags: ["download"],
    status: "accepted",
  },
  {
    id: "database-import",
    area: "library-data",
    workflow:
      "Import Database via filechooser: adds items, overwrites existing, pre-restore Backup; persists: yes",
    edges: ["Invalid file shows settings.importDatabaseFailed, Library untouched"],
    terms: ["Database File", "Backup", "Library"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "backupsPresent",
    tags: ["filechooser"],
    status: "accepted",
  },
  {
    id: "library-reset",
    area: "library-data",
    workflow:
      "Reset Library (type confirm?) clears Books/Notes/Canvases/history/metrics; settings kept; asserts: Confirm dialog focus inside; persists: yes",
    edges: ["Cancel"],
    terms: ["Reset", "Library", "Book", "Note", "Canvas"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "backupsPresent",
    tags: [],
    status: "accepted",
  },
  {
    id: "settings-theme",
    area: "settings",
    workflow: "Light/dark/system control by keyboard; asserts: html class; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "settings-primary-color",
    area: "settings",
    workflow: "Primary color picker by keyboard; asserts: CSS var value; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "settings-language",
    area: "settings",
    workflow:
      'Language select to Español: UI copy switches ("Libros"); back to English; asserts: heading text; persists: yes',
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "settings-editor-defaults",
    area: "settings",
    workflow:
      "Font, font size, default format, auto save, editor auto-close, hide keyboard hints, dictionary open-in-browser switches; asserts: Switch toggled by Space; persists: yes",
    edges: [],
    terms: [],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "settings-paste-cleanup",
    area: "settings",
    workflow:
      "Preset select; manage rules: add, edit, enable, move up/down, remove; strip properties add/remove; persists: yes",
    edges: [],
    terms: ["Paste Cleanup"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "settings-metrics",
    area: "settings",
    workflow:
      "Metrics Categories toggles; disable confirm dialog; asserts: Dialog focus; persists: yes",
    edges: ["Cancel"],
    terms: ["Metrics Category"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "metrics-collect",
    area: "metrics",
    workflow:
      "Write N words across fixed-clock days; Metrics shows total words, WPM, Streak, per-book list, time of day; asserts: Text values; persists: yes",
    edges: ["Disabled categories show metrics.disabledEmpty"],
    terms: ["Writing Session", "Streak", "Metrics Category", "Book", "Library"],
    shortcuts: [],
    routes: ["/metrics"],
    fixture: "metricsHistory",
    tags: ["clock"],
    status: "accepted",
  },
  {
    id: "metrics-streak-break",
    area: "metrics",
    workflow: "Skip a day: Current streak resets",
    edges: [],
    terms: ["Streak"],
    shortcuts: [],
    routes: ["/metrics"],
    fixture: "metricsHistory",
    tags: ["clock"],
    status: "accepted",
  },
  {
    id: "metrics-heatmap",
    area: "metrics",
    workflow:
      "Tab reaches the Heatmap grid once; arrows move day to day (Up/Down within week, Left/Right across weeks); focused day shows its Tooltip text <date>: N words; asserts: activeElement = day cell; grid has accessible name",
    edges: ["Empty year shows 0 words"],
    terms: [],
    shortcuts: [],
    routes: ["/metrics"],
    fixture: "metricsHistory",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-offer",
    area: "tutorial",
    workflow:
      "Empty Library, clean progress: offer shown; accept by keyboard; asserts: Offer focus",
    edges: ["Decline: dismissed", "not shown after reload"],
    terms: ["Tutorial", "Library"],
    shortcuts: [],
    routes: ["/"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-full-run",
    area: "tutorial",
    workflow:
      "Walk every step with Enter/Space on Next; asserts: Card focus on Next each step (#193); app inert outside card",
    edges: [],
    terms: ["Tutorial", "Tutorial Library"],
    shortcuts: [],
    routes: ["/"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-skip-esc",
    area: "tutorial",
    workflow: "Esc skips at any step; author Library back; asserts: Focus restoration",
    edges: [],
    terms: ["Tutorial", "Tutorial Library", "Library"],
    shortcuts: ["tutorial.skip"],
    routes: ["/"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-shortcut",
    area: "tutorial",
    workflow: "g u starts it",
    edges: [],
    terms: ["Tutorial"],
    shortcuts: ["global.startTutorial"],
    routes: ["/"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-settings-start-all",
    area: "tutorial",
    workflow:
      'Settings "Start all" with seeded Library: full run, Library byte-identical in IndexedDB; persists: yes',
    edges: [],
    terms: ["Tutorial", "Library", "Tutorial Library"],
    shortcuts: [],
    routes: ["/settings", "/"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-settings-section",
    area: "tutorial",
    workflow:
      'Start one section from Settings; only that section runs; marked "done"; persists: yes',
    edges: [],
    terms: ["Tutorial"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-dictation-section",
    area: "tutorial",
    workflow:
      'Settings → Tutorial "Dictation" row by keyboard; walks the six Dictation steps to Done without starting Dictation',
    edges: [],
    terms: [
      "Dictation",
      "Dictation Session",
      "Dictation Model",
      "Dictation Language",
      "Dictation Command Interpreter",
      "Spoken Punctuation",
      "Voice Command",
      "Dictation Vocabulary",
    ],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-settings-esc",
    area: "tutorial",
    workflow: "Esc mid-run returns to Settings, focus on launching button, section not done",
    edges: [],
    terms: ["Tutorial"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-settings-restart-done",
    area: "tutorial",
    workflow: "Restart a done section",
    edges: [],
    terms: ["Tutorial"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-reload-mid-run",
    area: "tutorial",
    workflow:
      "Reload during run returns to author Library; asserts: Library data asserted; persists: yes",
    edges: [],
    terms: ["Tutorial", "Tutorial Library", "Library"],
    shortcuts: [],
    routes: ["/"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "tutorial-isolation",
    area: "tutorial",
    workflow:
      "During run: no Backup created, no metrics recorded, no Reading Position saved; asserts: IndexedDB unchanged",
    edges: [],
    terms: ["Tutorial Library", "Tutorial"],
    shortcuts: [],
    routes: ["/"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "embed-editor",
    area: "embed",
    workflow:
      "/embed?theme=dark: editor usable by keyboard, theme applied, shortcuts work; persists: - (no persistence by design)",
    edges: ["theme=system follows emulated color scheme"],
    terms: [],
    shortcuts: [],
    routes: ["/embed"],
    fixture: "empty",
    tags: [],
    status: "accepted",
  },
  {
    id: "dictation-toggle",
    area: "editor",
    workflow:
      "Open a Chapter, Mod+Shift+Space starts Dictation (live region: Dictation on, English), speech lands at the caret as text, Escape stops (Dictation off), Mod+Z removes the last spoken line",
    edges: [
      "the floating mic button toggles the same session by Enter",
      "the language picker switches language with arrow keys",
      "Cycle Dictation language, bound in the Shortcut Editor, cycles the picker Auto -> en -> Auto and announces each step",
      "the bar keeps the same width across picker values",
      "with no model downloaded, Mod+Shift+Space shows the no-model hint and the mic leads to Settings",
      "WebKit shows no dictation control (not cross-origin isolated without credentialless)",
    ],
    terms: ["Dictation", "Dictation Session", "Dictation Language"],
    shortcuts: ["dictation.toggle", "dictation.stop", "dictation.cycleLanguage"],
    routes: ["/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
  {
    id: "dictation-settings",
    area: "settings",
    workflow:
      "Settings → Dictation: Tab to English Fast, Enter downloads with progress, the row shows Downloaded; Remove by keyboard returns it to Download",
    edges: [
      "Cancel during download leaves the model not downloaded",
      "a failed download (fixture 404) shows the error toast and a Download button again",
      "turning Dictation off removes the bar and Start or stop Dictation does nothing; turning it on restores both and keeps the downloaded models",
      "one Dictation Language tab list scopes the models, Spoken punctuation, and Dictation vocabulary",
    ],
    terms: ["Dictation Model"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
  {
    id: "shortcut-editor-voice-commands",
    area: "shell",
    workflow:
      "Shortcut Editor: a voice-eligible Command's row shows its Voice commands for the current Dictation Language; Voice opens a dialog to add, edit, remove, and reset phrases, with a switch to the other Dictation Language, all by keyboard; persists: yes (device-local, travels in the Shortcut File)",
    edges: [
      "a one-word phrase is refused with an alert",
      "a phrase that is another Command's Voice Command or Spoken Punctuation is refused with an alert",
      "Escape leaves an edit without closing the dialog, then closes it back to the row's Voice button",
      "the other Dictation Language keeps its own list",
      "custom Voice commands survive a reload and travel in the Shortcut File",
    ],
    terms: ["Voice Command", "Shortcut Editor", "Dictation Language", "Shortcut File"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: [],
    status: "accepted",
  },
  {
    id: "voice-commands-app",
    area: "shell",
    workflow:
      'A Chapter is open and Dictation is listening; the microphone says a Command\'s label ("Dark theme"); asserts: the html element takes the dark class, the Dictation live region announces "Voice command: Dark", and the Chapter text never holds the spoken words',
    edges: [
      'a navigating Voice Command ("Go to Notes") said over an open dialog closes the dialog and shows the Notes gallery, and the Chapter text never holds the spoken words',
      "a dialog that cannot close keeps the route and stays open (no shipped holdable dialog yet: https://github.com/M4ss1ck/maibuk/issues/328)",
      'a navigating Voice Command ("Go to Ephemeral") hands Dictation to the editor that takes the caret there: the sentence after the pause lands in it and Dictation stays on',
      'a navigating Voice Command to a screen with no editor ("Go to Settings") stops Dictation and the live region announces the handoff message',
    ],
    terms: ["Voice Command", "Dictation"],
    shortcuts: ["dictation.toggle"],
    routes: ["/settings", "/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
  {
    id: "voice-focus-keys",
    area: "shell",
    workflow:
      'A Chapter is open and Dictation is listening; the microphone says a focus key\'s label ("Press Tab", "Press Shift Tab", "Press Up", "Press Down", "Press Left", "Press Right", "Press Home", "Press End", "Press Enter", "Press Space", "Press Escape"); asserts: focus moves to the asserted element, the dialog closes, the menu item focuses, or the control activates, the Dictation live region announces the Command, and the Chapter text never holds the spoken words',
    edges: [
      "Tab in Book Settings moves from Book Title to Subtitle; Shift Tab moves back",
      "Down and Up move between Chapter rows; End and Home move to the last and first row",
      "Enter on a Chapter row opens it; Space on the delete confirm's No keeps the Chapter",
      "Escape closes the shortcuts help and returns focus to its trigger",
      "Left and Right move inside the editor toolbar",
    ],
    terms: ["Voice Command", "Dictation"],
    shortcuts: [
      "focus.next",
      "focus.previous",
      "focus.up",
      "focus.down",
      "focus.left",
      "focus.right",
      "focus.first",
      "focus.last",
      "focus.activate",
      "focus.toggle",
      "focus.escape",
    ],
    routes: ["/settings", "/book/:bookId"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
  {
    id: "dictation-spoken-punctuation",
    area: "settings",
    workflow:
      "Settings → Dictation: the Spoken punctuation list shows each entry's phrases and what it inserts for the chosen Dictation Language, with a master switch, a switch per entry, extra phrases, and reset, all by keyboard",
    edges: [
      "the list follows the Dictation Language tab chosen by arrow keys",
      "each language's list starts collapsed and expands and collapses by keyboard",
      "an entry switch and the master switch switch matching off, and the master disables the entry switches",
      "an extra phrase is added and removed by keyboard",
      "an extra phrase that is already a phrase, or starts with the escape word, is refused with an alert",
      "reset brings one entry's switch and phrases back to the defaults",
      "the settings stay per language and survive a reload",
    ],
    terms: ["Spoken Punctuation", "Dictation Language", "Dictation"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
  {
    id: "dictation-vocabulary",
    area: "settings",
    workflow:
      "Settings → Dictation: the Dictation vocabulary editor adds, edits, and removes an entry — what the model hears → what to write — for the chosen Dictation Language, all by keyboard",
    edges: [
      "an entry is added by keyboard and shown as heard → written",
      "an entry that repeats a heard form, folded, is refused with an alert",
      "an entry is edited in place and removed by keyboard",
      "the entries stay per Dictation Language tab chosen by arrow keys and survive a reload",
    ],
    terms: ["Dictation Vocabulary", "Dictation Language", "Dictation"],
    shortcuts: [],
    routes: ["/settings"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
  {
    id: "dictation-interpreter-stats",
    area: "settings",
    workflow:
      "Dictate a finished line into a Chapter, then open Settings → Dictation and read the interpreter delay and spoken punctuation count from this app session",
    edges: ["the numbers stay on this device and reset when the app reloads"],
    terms: ["Dictation Command Interpreter", "Spoken Punctuation"],
    shortcuts: ["dictation.toggle", "dictation.stop"],
    routes: ["/book/:bookId", "/settings"],
    fixture: "oneBookThreeChapters",
    tags: ["chromium-only"],
    status: "accepted",
  },
];
