import type { Settings } from "@/features/settings/types";
import type { SettingsRowId } from "@/components/settings/settings-sections";

/**
 * Which Settings row shows each Settings store key, or "internal" for UI
 * state no author would look for (sidebar widths, filters, view modes, last
 * path, presets...). A new key fails tsc until it is classified here.
 */
export const SETTINGS_KEY_ROWS = {
  appFontSize: "appFontSize",
  appFont: "appFont",
  primaryColor: "primaryColor",
  autoSave: "autoSave",
  alwaysOnTop: "alwaysOnTop",
  launchOnStartup: "launchOnStartup",
  closeToTray: "closeToTray",
  language: "language",
  spellCheckEnabled: "spellCheck",
  customDictionary: "customDictionary",
  dictionaryOpenInBrowser: "dictionaryOpenInBrowser",
  lastSceneBreak: "internal",
  sceneBreakPresets: "internal",
  showInlineFootnotes: "showInlineFootnotes",
  showNotesChapter: "showNotesChapter",
  bookSidePanelTab: "internal",
  hideKeyboardHints: "hideKeyboardHints",
  defaultExportFormat: "defaultExportFormat",
  backupRetention: "backupRetention",
  backupDirectory: "backupDirectory",
  backupListPage: "backupsList",
  backupListPageSize: "backupsList",
  mainSidebarWidth: "internal",
  sidebarWidth: "internal",
  notesSidebarWidth: "internal",
  toolbarExpanded: "internal",
  toolbarConfig: "internal",
  editorContentWidth: "internal",
  editorPagePadding: "internal",
  editorShowBorder: "internal",
  editorAutoClose: "editorAutoClose",
  chapterListView: "internal",
  showChapterOutline: "internal",
  notesListView: "internal",
  notesSort: "internal",
  notesFilters: "internal",
  booksStatusFilter: "internal",
  canvasSearch: "internal",
  notesTreeGroupMode: "internal",
  notesCollapsedGroups: "internal",
  notesExpandedEmptyGroups: "internal",
  htmlEditorLightTheme: "internal",
  htmlEditorDarkTheme: "internal",
  htmlPanelHeight: "internal",
  editorZoom: "internal",
  pasteCleanup: "pasteCleanupPreset",
  promptMarkdownOnPaste: "pasteCleanupPromptMarkdown",
  metrics: "metricsWriting",
  autoSync: "syncAutoSync",
} as const satisfies Record<keyof Settings, SettingsRowId | "internal">;
