// Generated by `pnpm generate:plugin-api` from src/features/plugins/api-table.ts. Do not edit.

import type { PluginStreamListener } from "@/plugin-sdk/protocol";

export const PLUGIN_API_VERSION = "0.1.0";

export const PLUGIN_API_METHODS = [
  "library.books.list",
  "library.books.get",
  "library.chapters.list",
  "library.chapters.get",
  "library.notes.list",
  "library.notes.get",
  "library.canvases.list",
  "library.canvases.get",
  "library.chapters.updateContent",
  "library.notes.create",
  "library.notes.update",
  "editor.getContent",
  "editor.getSelection",
  "editor.reveal",
  "editor.setHighlights",
  "editor.insert",
  "editor.replace",
  "navigation.openEntity",
  "secrets.set",
  "secrets.delete",
  "secrets.listNames",
  "network.fetch",
  "clipboard.readText",
  "clipboard.writeText",
  "notifications.show",
  "storage.get",
  "storage.set",
  "storage.delete",
  "storage.keys",
] as const;

export type PluginApiMethodId = (typeof PLUGIN_API_METHODS)[number];

/** Methods whose response body arrives as chunks after the call resolves. */
export const PLUGIN_API_STREAMING_METHODS = [
  "network.fetch",
] as const;

export interface PluginApiMethods {
  /** Lists every Book in the Library. */
  "library.books.list": {
    input: Record<string, never>;
    output: {
      id: string;
      title: string;
      subtitle: string | null;
      authorName: string;
      language: string;
      wordCount: number;
      /** Milliseconds since the Unix epoch. */
      updatedAt: number;
    }[];
  };
  /** Reads one Book's details, or null when it does not exist. */
  "library.books.get": {
    input: {
      bookId: string;
    };
    output: {
      id: string;
      title: string;
      subtitle: string | null;
      authorName: string;
      language: string;
      wordCount: number;
      /** Milliseconds since the Unix epoch. */
      updatedAt: number;
    } | null;
  };
  /** Lists a Book's Chapters in order, without their content. */
  "library.chapters.list": {
    input: {
      bookId: string;
    };
    output: {
      id: string;
      bookId: string;
      title: string;
      order: number;
      parentId: string | null;
      wordCount: number;
      /** Milliseconds since the Unix epoch. */
      updatedAt: number;
    }[];
  };
  /** Reads one Chapter with its content as plain text and sanitized HTML. */
  "library.chapters.get": {
    input: {
      chapterId: string;
    };
    output: {
      id: string;
      bookId: string;
      title: string;
      order: number;
      parentId: string | null;
      wordCount: number;
      /** Milliseconds since the Unix epoch. */
      updatedAt: number;
      content: {
        /** Plain text. */
        text: string;
        /** Sanitized HTML. */
        html: string;
      };
    } | null;
  };
  /** Lists Notes, all of them or one Book's, without their content. */
  "library.notes.list": {
    input: {
      bookId?: string;
    };
    output: {
      id: string;
      bookId: string | null;
      title: string;
      tags: string[];
      wordCount: number;
      /** Milliseconds since the Unix epoch. */
      updatedAt: number;
    }[];
  };
  /** Reads one Note with its content as plain text and sanitized HTML. */
  "library.notes.get": {
    input: {
      noteId: string;
    };
    output: {
      id: string;
      bookId: string | null;
      title: string;
      tags: string[];
      wordCount: number;
      /** Milliseconds since the Unix epoch. */
      updatedAt: number;
      content: {
        /** Plain text. */
        text: string;
        /** Sanitized HTML. */
        html: string;
      };
    } | null;
  };
  /** Lists Canvases with their metadata. Canvas content is not part of the API. */
  "library.canvases.list": {
    input: {
      bookId?: string;
    };
    output: {
      id: string;
      bookId: string | null;
      title: string;
      /** Milliseconds since the Unix epoch. */
      updatedAt: number;
    }[];
  };
  /** Reads one Canvas's metadata, or null when it does not exist. */
  "library.canvases.get": {
    input: {
      canvasId: string;
    };
    output: {
      id: string;
      bookId: string | null;
      title: string;
      /** Milliseconds since the Unix epoch. */
      updatedAt: number;
    } | null;
  };
  /** Replaces a Chapter's content through the Chapter write path. */
  "library.chapters.updateContent": {
    input: {
      chapterId: string;
      /** Plain text, or an HTML fragment the host sanitizes. */
      content: {
        text: string;
      } | {
        /** Sanitized by the host before it lands. */
        html: string;
      };
    };
    output: null;
  };
  /** Creates a Note through the Note write path and returns its id. */
  "library.notes.create": {
    input: {
      title: string;
      bookId?: string | null;
      /** Plain text, or an HTML fragment the host sanitizes. */
      content?: {
        text: string;
      } | {
        /** Sanitized by the host before it lands. */
        html: string;
      };
    };
    output: {
      noteId: string;
    };
  };
  /** Updates a Note's title or content through the Note write path. */
  "library.notes.update": {
    input: {
      noteId: string;
      title?: string;
      /** Plain text, or an HTML fragment the host sanitizes. */
      content?: {
        text: string;
      } | {
        /** Sanitized by the host before it lands. */
        html: string;
      };
    };
    output: null;
  };
  /** Reads the focused rich-text editor's content, or no-target when none is focused. */
  "editor.getContent": {
    input: Record<string, never>;
    output: {
      status: "ok";
      entity: {
        kind: "book" | "chapter" | "note" | "canvas";
        id: string;
      };
      content: {
        /** Plain text. */
        text: string;
        /** Sanitized HTML. */
        html: string;
      };
    } | {
      status: "no-target";
    };
  };
  /** Reads the focused editor's selection as plain-text offsets. */
  "editor.getSelection": {
    input: Record<string, never>;
    output: {
      status: "ok";
      entity: {
        kind: "book" | "chapter" | "note" | "canvas";
        id: string;
      };
      range: {
        from: number;
        to: number;
      };
      text: string;
    } | {
      status: "no-target";
    };
  };
  /** Scrolls the focused editor to a range and places the caret there. */
  "editor.reveal": {
    input: {
      range: {
        from: number;
        to: number;
      };
    };
    output: {
      status: "applied";
    } | {
      status: "no-target";
    };
  };
  /** Replaces this Plugin's whole set of highlights in the focused editor. Never changes text. */
  "editor.setHighlights": {
    input: {
      kind: "info" | "warning" | "repetition";
      ranges: {
        from: number;
        to: number;
        label?: string;
      }[];
    };
    output: {
      status: "applied";
    } | {
      status: "no-target";
    };
  };
  /** Inserts text or an HTML fragment at the caret as one undoable step. */
  "editor.insert": {
    input: {
      /** Plain text, or an HTML fragment the host sanitizes. */
      content: {
        text: string;
      } | {
        /** Sanitized by the host before it lands. */
        html: string;
      };
    };
    output: {
      status: "applied";
    } | {
      status: "no-target";
    };
  };
  /** Replaces a range with text or an HTML fragment as one undoable step. */
  "editor.replace": {
    input: {
      range: {
        from: number;
        to: number;
      };
      /** Plain text, or an HTML fragment the host sanitizes. */
      content: {
        text: string;
      } | {
        /** Sanitized by the host before it lands. */
        html: string;
      };
    };
    output: {
      status: "applied";
    } | {
      status: "no-target";
    };
  };
  /** Opens a Book, Chapter, Note, or Canvas, optionally revealing a range. */
  "navigation.openEntity": {
    input: {
      entity: {
        kind: "book" | "chapter" | "note" | "canvas";
        id: string;
      };
      reveal?: {
        from: number;
        to: number;
      };
    };
    output: null;
  };
  /** Stores a secret by name. Secrets are never read back into the Plugin. */
  "secrets.set": {
    input: {
      name: string;
      value: string;
    };
    output: null;
  };
  /** Deletes a stored secret by name. */
  "secrets.delete": {
    input: {
      name: string;
    };
    output: null;
  };
  /** Lists the names of this Plugin's stored secrets, never their values. */
  "secrets.listNames": {
    input: Record<string, never>;
    output: string[];
  };
  /** Fetches a URL on a granted host. A header can name a stored secret the host injects. */
  "network.fetch": {
    input: {
      url: string;
      method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD";
      headers?: Record<string, string>;
      /** Header name to secret name; the host fills in the value. */
      secretHeaders?: Record<string, string>;
      body?: string;
    };
    output: {
      status: number;
      statusText: string;
      headers: Record<string, string>;
    };
    chunk: {
      /** The next piece of the response body, decoded as UTF-8. A chunk is at most 64 KB. */
      text: string;
    };
  };
  /** Reads plain text from the clipboard. */
  "clipboard.readText": {
    input: Record<string, never>;
    output: string;
  };
  /** Writes plain text to the clipboard. */
  "clipboard.writeText": {
    input: {
      text: string;
    };
    output: null;
  };
  /** Shows a toast naming this Plugin. At most one every 5 seconds. */
  "notifications.show": {
    input: {
      variant: "info" | "success" | "warning" | "error";
      message: string;
    };
    output: null;
  };
  /** Reads a JSON value from this Plugin's storage, or null when the key is unset. */
  "storage.get": {
    input: {
      key: string;
    };
    output: unknown;
  };
  /** Stores a JSON value in this Plugin's storage. */
  "storage.set": {
    input: {
      key: string;
      value: unknown;
    };
    output: null;
  };
  /** Deletes a key from this Plugin's storage. */
  "storage.delete": {
    input: {
      key: string;
    };
    output: null;
  };
  /** Lists every key in this Plugin's storage. */
  "storage.keys": {
    input: Record<string, never>;
    output: string[];
  };
}

export const PLUGIN_API_EVENT_IDS = [
  "library.changed",
  "library.availabilityChanged",
  "editor.contentChanged",
  "editor.focusChanged",
] as const;

export type PluginApiEventId = (typeof PLUGIN_API_EVENT_IDS)[number];

/** Event payloads. Events only invalidate: they carry ids, never content. */
export interface PluginApiEvents {
  /** A Book, Note, or Canvas was saved (Chapter edits arrive as their Book), or a bulk operation replaced the Library. */
  "library.changed": {
    entity: "book" | "note" | "canvas";
    id: string;
    origin: "local" | "remote";
    kind: "content" | "metadata";
  } | {
    scope: "all";
    reason: "restore" | "resetLibrary" | "databaseLoad";
  };
  /** The Library became available or unavailable (the Tutorial makes it unavailable). */
  "library.availabilityChanged": {
    available: boolean;
  };
  /** The focused editor's content changed; sent once per typing burst. */
  "editor.contentChanged": {
    entity: {
      kind: "book" | "chapter" | "note" | "canvas";
      id: string;
    };
  };
  /** A different editor took focus, or none did (entity is null). */
  "editor.focusChanged": {
    entity: {
      kind: "book" | "chapter" | "note" | "canvas";
      id: string;
    } | null;
  };
}

export interface PluginApi {
  library: {
    books: {
      /** Lists every Book in the Library. */
      list(params?: PluginApiMethods["library.books.list"]["input"]): Promise<PluginApiMethods["library.books.list"]["output"]>;
      /** Reads one Book's details, or null when it does not exist. */
      get(params: PluginApiMethods["library.books.get"]["input"]): Promise<PluginApiMethods["library.books.get"]["output"]>;
    };
    chapters: {
      /** Lists a Book's Chapters in order, without their content. */
      list(params: PluginApiMethods["library.chapters.list"]["input"]): Promise<PluginApiMethods["library.chapters.list"]["output"]>;
      /** Reads one Chapter with its content as plain text and sanitized HTML. */
      get(params: PluginApiMethods["library.chapters.get"]["input"]): Promise<PluginApiMethods["library.chapters.get"]["output"]>;
      /** Replaces a Chapter's content through the Chapter write path. */
      updateContent(params: PluginApiMethods["library.chapters.updateContent"]["input"]): Promise<PluginApiMethods["library.chapters.updateContent"]["output"]>;
    };
    notes: {
      /** Lists Notes, all of them or one Book's, without their content. */
      list(params?: PluginApiMethods["library.notes.list"]["input"]): Promise<PluginApiMethods["library.notes.list"]["output"]>;
      /** Reads one Note with its content as plain text and sanitized HTML. */
      get(params: PluginApiMethods["library.notes.get"]["input"]): Promise<PluginApiMethods["library.notes.get"]["output"]>;
      /** Creates a Note through the Note write path and returns its id. */
      create(params: PluginApiMethods["library.notes.create"]["input"]): Promise<PluginApiMethods["library.notes.create"]["output"]>;
      /** Updates a Note's title or content through the Note write path. */
      update(params: PluginApiMethods["library.notes.update"]["input"]): Promise<PluginApiMethods["library.notes.update"]["output"]>;
    };
    canvases: {
      /** Lists Canvases with their metadata. Canvas content is not part of the API. */
      list(params?: PluginApiMethods["library.canvases.list"]["input"]): Promise<PluginApiMethods["library.canvases.list"]["output"]>;
      /** Reads one Canvas's metadata, or null when it does not exist. */
      get(params: PluginApiMethods["library.canvases.get"]["input"]): Promise<PluginApiMethods["library.canvases.get"]["output"]>;
    };
  };
  editor: {
    /** Reads the focused rich-text editor's content, or no-target when none is focused. */
    getContent(params?: PluginApiMethods["editor.getContent"]["input"]): Promise<PluginApiMethods["editor.getContent"]["output"]>;
    /** Reads the focused editor's selection as plain-text offsets. */
    getSelection(params?: PluginApiMethods["editor.getSelection"]["input"]): Promise<PluginApiMethods["editor.getSelection"]["output"]>;
    /** Scrolls the focused editor to a range and places the caret there. */
    reveal(params: PluginApiMethods["editor.reveal"]["input"]): Promise<PluginApiMethods["editor.reveal"]["output"]>;
    /** Replaces this Plugin's whole set of highlights in the focused editor. Never changes text. */
    setHighlights(params: PluginApiMethods["editor.setHighlights"]["input"]): Promise<PluginApiMethods["editor.setHighlights"]["output"]>;
    /** Inserts text or an HTML fragment at the caret as one undoable step. */
    insert(params: PluginApiMethods["editor.insert"]["input"]): Promise<PluginApiMethods["editor.insert"]["output"]>;
    /** Replaces a range with text or an HTML fragment as one undoable step. */
    replace(params: PluginApiMethods["editor.replace"]["input"]): Promise<PluginApiMethods["editor.replace"]["output"]>;
  };
  navigation: {
    /** Opens a Book, Chapter, Note, or Canvas, optionally revealing a range. */
    openEntity(params: PluginApiMethods["navigation.openEntity"]["input"]): Promise<PluginApiMethods["navigation.openEntity"]["output"]>;
  };
  secrets: {
    /** Stores a secret by name. Secrets are never read back into the Plugin. */
    set(params: PluginApiMethods["secrets.set"]["input"]): Promise<PluginApiMethods["secrets.set"]["output"]>;
    /** Deletes a stored secret by name. */
    delete(params: PluginApiMethods["secrets.delete"]["input"]): Promise<PluginApiMethods["secrets.delete"]["output"]>;
    /** Lists the names of this Plugin's stored secrets, never their values. */
    listNames(params?: PluginApiMethods["secrets.listNames"]["input"]): Promise<PluginApiMethods["secrets.listNames"]["output"]>;
  };
  network: {
    /** Fetches a URL on a granted host. A header can name a stored secret the host injects. */
    fetch(params: PluginApiMethods["network.fetch"]["input"], listener?: PluginStreamListener<PluginApiMethods["network.fetch"]["chunk"]>): Promise<PluginApiMethods["network.fetch"]["output"]>;
  };
  clipboard: {
    /** Reads plain text from the clipboard. */
    readText(params?: PluginApiMethods["clipboard.readText"]["input"]): Promise<PluginApiMethods["clipboard.readText"]["output"]>;
    /** Writes plain text to the clipboard. */
    writeText(params: PluginApiMethods["clipboard.writeText"]["input"]): Promise<PluginApiMethods["clipboard.writeText"]["output"]>;
  };
  notifications: {
    /** Shows a toast naming this Plugin. At most one every 5 seconds. */
    show(params: PluginApiMethods["notifications.show"]["input"]): Promise<PluginApiMethods["notifications.show"]["output"]>;
  };
  storage: {
    /** Reads a JSON value from this Plugin's storage, or null when the key is unset. */
    get(params: PluginApiMethods["storage.get"]["input"]): Promise<PluginApiMethods["storage.get"]["output"]>;
    /** Stores a JSON value in this Plugin's storage. */
    set(params: PluginApiMethods["storage.set"]["input"]): Promise<PluginApiMethods["storage.set"]["output"]>;
    /** Deletes a key from this Plugin's storage. */
    delete(params: PluginApiMethods["storage.delete"]["input"]): Promise<PluginApiMethods["storage.delete"]["output"]>;
    /** Lists every key in this Plugin's storage. */
    keys(params?: PluginApiMethods["storage.keys"]["input"]): Promise<PluginApiMethods["storage.keys"]["output"]>;
  };
}
